### PR TITLE
Add dashboard to the public repo

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Review by llorracc — COMMENTED** [review]
Sorry, forgot my script does not copy dashboard stuff from private to public repo.  Will fix.

But, first, we should settle on the standard for:
1. Location
2. Name 

of dashboards such that, if there is a dashboard there, econ-ark.org will find it without the need for it to be in the markdown metadata file.  

My instinct is that if the repo root is ., the default should be ./[materialname]-Dashboard.ipynb and the other other required files should be in a folder ./[materialname]-Dashboard/.  Other arrangements would be OK too- if you and Andrij have reasons for doing it differently that's fine.  

But, whatever you decide, I'd like to get this done in the private repo today, and then will make sure my script will copy to the public one.  (The reason the script didn't copy it is that in order to write the script robustly (so that it will work for other private repos), I need the script programmatically to know where to look for things).

**Comment by MridulS** [comment]
The website works independently of the Location and Name. The structure of how and where to put the dashboard is an aesthetic design choice. What the website does look for is the exact path in the markdown metadata file, so it's perfectly fine to have `Code/Python/[materialname]-Dashboard.ipynb` or `./[materialname]-Dashboard.ipynb`. The only thing required to make the website work would be the correct path to the dashboard in the metadata.

**Comment by MridulS** [comment]
IMO `Code/Python/BufferStockTheory-Interactive-Dashboard.ipynb` is fine.

**Comment by MridulS** [comment]
new public repo https://github.com/llorracc/BufferStockTheory already has the correct notebooks, no need for this PR.

**Pull request closed without merging**
